using System;
using System.Collections.Generic;

namespace Poke_Edit
{
    public class PokeList
    {
        static Bindings<short, ushort> pokeList = new Bindings<short, ushort>(sizeA:440, sizeB:388);
        static bool isInit = false;
      

        public static short GetDex(ushort species) {
            if (!isInit)
                Init();
            return pokeList.SideA[species];
        }

        public static ushort GetSpecies(short dexNum) {
            if (!isInit)
                Init();
            return pokeList.SideB[dexNum];
        }

        static void Init()
        {
            for (short i = 0; i < pokeList.SideA.Length; i++) {
                if (i > 251 && i < 277)
                    pokeList.SideA[i] = 0;
                else if (i <= 300)
                    pokeList.SideA[i] = (short)(i >= 277 ? i - 25 : i);
                else
                    pokeList.SideA[i] = (short)(i > 412 ? 201 : gen3Dex[(Pkm)i]);
            }

            for (ushort j = 0; j < pokeList.SideB.Length; j++) {
                if (j > 275)
                    break;

                pokeList.SideB[j] = (ushort)(j > 251 ? j + 25 : j);
            }

            isInit = true;
        }

        static Dictionary<Pkm, short> gen3Dex = new Dictionary<Pkm, short>() {
           { Pkm.Taillow , 276 },
           { Pkm.Swellow , 277 },
           { Pkm.Wingull , 278 },
           { Pkm.Pelipper , 279 },
           { Pkm.Ralts , 280 },
           { Pkm.Kirlia , 281 },
           { Pkm.Gardevoir , 282 },
           { Pkm.Surskit , 283 },
           { Pkm.Masquerain , 284 },
           { Pkm.Shroomish , 285 },
           { Pkm.Breloom , 286 },
           { Pkm.Slakoth , 287 },
           { Pkm.Vigoroth , 288 },
           { Pkm.Slaking, 289 },
           { Pkm.Nincada , 290 },
           { Pkm.Ninjask , 291 },
           { Pkm.Shedinja , 292 },
           { Pkm.Whismur , 293 },
           { Pkm.Loudred , 294 },
           { Pkm.Exploud , 295 },
           { Pkm.Makuhita , 296 },
           { Pkm.Hariyama , 297 },
           { Pkm.Azurill , 298 },
           { Pkm.Nosepass , 299 },
           { Pkm.Skitty , 300 },
           { Pkm.Delcatty , 301 },
           { Pkm.Sableye , 302 },
           { Pkm.Mawile , 303 },
           { Pkm.Aron , 304 },
           { Pkm.Lairon , 305 },
           { Pkm.Aggron , 306 },
           { Pkm.Meditite , 307 },
           { Pkm.Medicham , 308 },
           { Pkm.Electrike , 309 },
           { Pkm.Manectric , 310 },
           { Pkm.Plusle , 311 },
           { Pkm.Minun , 312 },
           { Pkm.Volbeat , 313 },
           { Pkm.Illumise , 314 },
           { Pkm.Roselia , 315 },
           { Pkm.Gulpin , 316 },
           { Pkm.Swalot , 317 },
           { Pkm.Carvanha , 318 },
           { Pkm.Sharpedo , 319 },
           { Pkm.Wailmer , 320 },
           { Pkm.Wailord , 321 },
           { Pkm.Numel , 322 },
           { Pkm.Camerupt , 323 },
           { Pkm.Torkoal , 324 },
           { Pkm.Spoink , 325 },
           { Pkm.Grumpig , 326 },
           { Pkm.Spinda , 327 },
           { Pkm.Trapinch , 328 },
           { Pkm.Vibrava , 329 },
           { Pkm.Flygon , 330 },
           { Pkm.Cacnea , 331 },
           { Pkm.Cacturne , 332 },
           { Pkm.Swablu , 333 },
           { Pkm.Altaria , 334 },
           { Pkm.Zangoose , 335 },
           { Pkm.Seviper , 336 },
           { Pkm.Lunatone , 337 },
           { Pkm.Solrock , 338 },
           { Pkm.Barboach , 339 },
           { Pkm.Whiscash , 340 },
           { Pkm.Corphish , 341 },
           { Pkm.Crawdaunt , 342 },
           { Pkm.Baltoy , 343 },
           { Pkm.Claydol , 344 },
           { Pkm.Lileep , 345 },
           { Pkm.Cradily , 346 },
           { Pkm.Anorith , 347 },
           { Pkm.Armaldo , 348 },
           { Pkm.Feebas , 349 },
           { Pkm.Milotic , 350 },
           { Pkm.Castform , 351 },
           { Pkm.Kecleon , 352 },
           { Pkm.Shuppet , 353 },
           { Pkm.Banette , 354 },
           { Pkm.Duskull , 355 },
           { Pkm.Dusclops , 356 },
           { Pkm.Tropius , 357 },
           { Pkm.Chimecho , 358 },
           { Pkm.Absol , 359 },
           { Pkm.Wynaut , 360 },
           { Pkm.Snorunt , 361 },
           { Pkm.Glalie , 362 },
           { Pkm.Spheal , 363 },
           { Pkm.Sealeo , 364 },
           { Pkm.Walrein , 365 },
           { Pkm.Clamperl , 366 },
           { Pkm.Huntail , 367 },
           { Pkm.Gorebyss , 368 },
           { Pkm.Relicanth , 369 },
           { Pkm.Luvdisc , 370 },
           { Pkm.Bagon , 371 },
           { Pkm.Shelgon , 372 },
           { Pkm.Salamence , 373 },
           { Pkm.Beldum , 374 },
           { Pkm.Metang , 375 },
           { Pkm.Metagross , 376 },
           { Pkm.Regirock , 377 },
           { Pkm.Regice , 378 },
           { Pkm.Registeel , 379 },
           { Pkm.Latias , 380 },
           { Pkm.Latios , 381 },
           { Pkm.Kyogre , 382 },
           { Pkm.Groudon , 383 },
           { Pkm.Rayquaza , 384 },
           { Pkm.Jirachi , 385 },
           { Pkm.Deoxys , 386 },
           { Pkm.Egg , 387 },
       };
    }

    public enum Pkm {
        Nincada = 301,
        Ninjask,
        Shedinja,
        Taillow,
        Swellow,
        Shroomish,
        Breloom,
        Spinda,
        Wingull,
        Pelipper,
        Surskit,
	    Masquerain,
        Wailmer,
        Wailord,
        Skitty,
        Delcatty,
        Kecleon,
        Baltoy,
        Claydol,
        Nosepass,
        Torkoal,
        Sableye,
        Barboach,
        Whiscash,
        Luvdisc,
        Corphish,
        Crawdaunt,
        Feebas,
        Milotic,
        Carvanha,
        Sharpedo,
        Trapinch,
        Vibrava,
        Flygon,
        Makuhita,
        Hariyama,
        Electrike,
        Manectric,
        Numel,
        Camerupt,
        Spheal,
        Sealeo,
        Walrein,
        Cacnea,
        Cacturne,
        Snorunt,
        Glalie,
        Lunatone,
        Solrock,
        Azurill,
        Spoink,
        Grumpig,
        Plusle,
        Minun,
        Mawile,
        Meditite,
        Medicham,
        Swablu,
        Altaria,
        Wynaut,
        Duskull,
        Dusclops,
        Roselia,
        Slakoth,
	    Vigoroth,
	    Slaking,
        Gulpin,
        Swalot,
        Tropius,
        Whismur,
	    Loudred,
	    Exploud,
        Clamperl,
        Huntail,
        Gorebyss,
        Absol,
        Shuppet,
        Banette,
        Seviper,
        Zangoose,
        Relicanth,
        Aron,
	    Lairon,
	    Aggron,
        Castform,
        Volbeat,
	    Illumise,
	    Lileep,
	    Cradily,
	    Anorith,
	    Armaldo,
        Ralts,
        Kirlia,
        Gardevoir,
	    Bagon,
	    Shelgon,
	    Salamence,
	    Beldum,
	    Metang,
	    Metagross,
	    Regirock,
	    Regice,
	    Registeel,
        Kyogre,
        Groudon,
        Rayquaza,
        Latias,
	    Latios,
	    Jirachi,
	    Deoxys,
        Chimecho,
        Egg,
        UnownB,
        UnownC,
        UnownD,
        UnownE,
        UnownF,
        UnownG,
        UnownH,
        UnownI,
        UnownJ,
        UnownK,
        UnownL,
        UnownM,
        UnownN,
        UnownO,
        UnownP,
        UnownQ,
        UnownR,
        UnownS,
        UnownT,
        UnownU,
        UnownV,
        UnownW,
        UnownX,
        UnownY,
        UnownZ,
        UnownExclamation,
        UnownQuestion
    }
}
